package com.visable.messaging.consts

const val UNIQUE_NICKNAME_1 = "unique nickName 1"
const val UNIQUE_NICKNAME_2 = "unique nickName 2"
const val UNIQUE_NICKNAME_3 = "unique nickName 3"
const val MESSAGE_SENDER_AND_RECEIVER_USER_SAME_ERROR = "The sender userId and the receiver userId shouldn't be same."
const val MESSAGE_SENDER_USER_NOT_FOUND_ERROR = "The sender userId is not found."
const val MESSAGE_RECEIVER_USER_NOT_FOUND_ERROR = "The receiver userId is not found."
const val USERS_ENDPOINT = "/api/v1/users"
const val MESSAGES_ENDPOINT = "/api/v1/messages"
const val ID = "id"
const val RECEIVED_DATE_TIME = "receivedDateTime"
const val NICKNAME_EXISTS_ERROR = "{\"errors\":[\"The nickName is already exist. Please enter another one.\"]}"
const val SENDER_AND_RECEIVER_USER_SAME_ERROR = "{\"errors\":[\"The sender userId and the receiver userId shouldn't be same.\"]}"
const val RECEIVER_USER_NOT_FOUND_ERROR = "{\"errors\":[\"The receiver userId is not found.\"]}"
const val SENDER_USER_NOT_FOUND_ERROR = "{\"errors\":[\"The sender userId is not found.\"]}"
const val USER_ID = "UserId"
const val SENT = "/sent"
const val RECEIVED_FROM = "/receivedFrom"
